import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  TextInput,
  Dimensions,
} from "react-native";
import { useRef, useState } from "react";
import { useRouter } from "expo-router";
import Animated, { FadeInDown, FadeOutUp } from "react-native-reanimated";
import { Colors, Spacing, Typography } from "@constants/theme";
import { Button } from "@components/Button";
import { completeOnboarding } from "@services/userPreferences";

const { height } = Dimensions.get("window");

type Screen = "welcome" | "promise" | "setup" | "referral";

export default function OnboardingScreen() {
  const router = useRouter();
  const scrollViewRef = useRef<ScrollView>(null);
  const [currentScreen, setCurrentScreen] = useState<Screen>("welcome");
  const [referralSource, setReferralSource] = useState("");

  const handleNext = () => {
    const screens: Screen[] = ["welcome", "promise", "setup", "referral"];
    const currentIndex = screens.indexOf(currentScreen);
    if (currentIndex < screens.length - 1) {
      setCurrentScreen(screens[currentIndex + 1]);
    }
  };

  const handleComplete = async () => {
    try {
      await completeOnboarding(referralSource || undefined);
      router.replace("/scan");
    } catch (error) {
      console.error("Failed to complete onboarding:", error);
    }
  };

  return (
    <ScrollView
      ref={scrollViewRef}
      style={styles.container}
      contentContainerStyle={styles.contentContainer}
      scrollEnabled={false}
    >
      {currentScreen === "welcome" && (
        <Animated.View entering={FadeInDown}>
          <Screen1 onNext={handleNext} />
        </Animated.View>
      )}

      {currentScreen === "promise" && (
        <Animated.View entering={FadeInDown}>
          <Screen2 onNext={handleNext} />
        </Animated.View>
      )}

      {currentScreen === "setup" && (
        <Animated.View entering={FadeInDown}>
          <Screen3 onNext={handleNext} />
        </Animated.View>
      )}

      {currentScreen === "referral" && (
        <Animated.View entering={FadeInDown}>
          <Screen4
            referralSource={referralSource}
            onChangeReferral={setReferralSource}
            onComplete={handleComplete}
          />
        </Animated.View>
      )}
    </ScrollView>
  );
}

// Screen 1: Welcome
function Screen1({ onNext }: { onNext: () => void }) {
  return (
    <View style={styles.screen}>
      <View style={styles.topSection}>
        <Text style={styles.emoji}>🌱</Text>
        <Text style={styles.title}>Welcome to Verdure</Text>
        <Text style={styles.subtitle}>The honest plant identification app</Text>
      </View>

      <View style={styles.middleSection}>
        <FeatureRow icon="📸" text="Identify plants from photos" />
        <FeatureRow icon="📚" text="Get curated care advice" />
        <FeatureRow icon="🌿" text="Track your plant collection" />
      </View>

      <View style={styles.bottomSection}>
        <Button label="Get Started" onPress={onNext} />
      </View>
    </View>
  );
}

// Screen 2: The Promise
function Screen2({ onNext }: { onNext: () => void }) {
  return (
    <View style={styles.screen}>
      <View style={styles.topSection}>
        <Text style={styles.emoji}>🤝</Text>
        <Text style={styles.title}>Our Promise</Text>
      </View>

      <View style={styles.middleSection}>
        <PromiseRow icon="✅" title="Never Fake Confidence">
          <Text style={styles.description}>
            We always show you when we're uncertain and give you alternatives.
          </Text>
        </PromiseRow>

        <PromiseRow icon="🔓" title="Never Trap You">
          <Text style={styles.description}>
            See pricing before you commit. Cancel anytime, right in the app.
          </Text>
        </PromiseRow>

        <PromiseRow icon="🎯" title="Never Give Bad Advice">
          <Text style={styles.description}>
            Our care guides are reviewed by experts, not generated by AI.
          </Text>
        </PromiseRow>
      </View>

      <View style={styles.bottomSection}>
        <Button label="Next" onPress={onNext} />
      </View>
    </View>
  );
}

// Screen 3: Setup
function Screen3({ onNext }: { onNext: () => void }) {
  const [hasChildren, setHasChildren] = useState(false);

  return (
    <View style={styles.screen}>
      <View style={styles.topSection}>
        <Text style={styles.emoji}>⚙️</Text>
        <Text style={styles.title}>Quick Setup</Text>
      </View>

      <View style={styles.middleSection}>
        <Text style={styles.setupQuestion}>Do you have kids or pets at home?</Text>
        <Text style={styles.setupSubtext}>
          This helps us warn you about toxic plants.
        </Text>

        <View style={styles.toggleButtons}>
          <TouchableOpacity
            style={[styles.toggleButton, !hasChildren && styles.toggleActive]}
            onPress={() => setHasChildren(false)}
          >
            <Text style={[styles.toggleText, !hasChildren && styles.toggleTextActive]}>
              No
            </Text>
          </TouchableOpacity>

          <TouchableOpacity
            style={[styles.toggleButton, hasChildren && styles.toggleActive]}
            onPress={() => setHasChildren(true)}
          >
            <Text style={[styles.toggleText, hasChildren && styles.toggleTextActive]}>
              Yes
            </Text>
          </TouchableOpacity>
        </View>
      </View>

      <View style={styles.bottomSection}>
        <Button label="Next" onPress={onNext} />
      </View>
    </View>
  );
}

// Screen 4: Referral & Complete
function Screen4({
  referralSource,
  onChangeReferral,
  onComplete,
}: {
  referralSource: string;
  onChangeReferral: (text: string) => void;
  onComplete: () => void;
}) {
  return (
    <View style={styles.screen}>
      <View style={styles.topSection}>
        <Text style={styles.emoji}>📲</Text>
        <Text style={styles.title}>Almost There!</Text>
      </View>

      <View style={styles.middleSection}>
        <Text style={styles.setupQuestion}>How did you find us?</Text>
        <Text style={styles.setupSubtext}>
          Help us understand which channels work. This is optional.
        </Text>

        <TextInput
          style={styles.referralInput}
          placeholder="E.g., App Store search, friend, TikTok..."
          value={referralSource}
          onChangeText={onChangeReferral}
          placeholderTextColor={Colors.textDisabled}
        />

        <Text style={styles.referralNote}>
          📝 We use this to improve our marketing, not to track you personally.
        </Text>
      </View>

      <View style={styles.bottomSection}>
        <Button label="Scan Your First Plant" onPress={onComplete} />
        <Text style={styles.disclaimer}>
          You'll need camera permission next. We don't store photos.
        </Text>
      </View>
    </View>
  );
}

// Helpers
function FeatureRow({ icon, text }: { icon: string; text: string }) {
  return (
    <View style={styles.featureRow}>
      <Text style={styles.featureIcon}>{icon}</Text>
      <Text style={styles.featureText}>{text}</Text>
    </View>
  );
}

function PromiseRow({
  icon,
  title,
  children,
}: {
  icon: string;
  title: string;
  children: React.ReactNode;
}) {
  return (
    <View style={styles.promiseRow}>
      <Text style={styles.promiseIcon}>{icon}</Text>
      <View style={styles.promiseContent}>
        <Text style={styles.promiseTitle}>{title}</Text>
        {children}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: Colors.background,
  },
  contentContainer: {
    minHeight: height,
  },
  screen: {
    flex: 1,
    height: height,
    paddingHorizontal: Spacing.default,
    justifyContent: "space-between",
    paddingVertical: Spacing.loose,
  },
  topSection: {
    alignItems: "center",
    marginTop: Spacing.spacious,
  },
  emoji: {
    fontSize: 64,
    marginBottom: Spacing.default,
  },
  title: {
    fontSize: Typography.display.fontSize,
    fontWeight: Typography.display.fontWeight as any,
    color: Colors.textPrimary,
    marginBottom: Spacing.tight,
    textAlign: "center",
  },
  subtitle: {
    fontSize: Typography.body.fontSize,
    color: Colors.textSecondary,
    textAlign: "center",
  },
  middleSection: {
    flex: 1,
    justifyContent: "center",
  },
  featureRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: Spacing.loose,
  },
  featureIcon: {
    fontSize: 32,
    marginRight: Spacing.default,
  },
  featureText: {
    fontSize: Typography.body.fontSize,
    color: Colors.textPrimary,
    flex: 1,
  },
  promiseRow: {
    flexDirection: "row",
    marginBottom: Spacing.spacious,
  },
  promiseIcon: {
    fontSize: 28,
    marginRight: Spacing.default,
    marginTop: Spacing.compact,
  },
  promiseContent: {
    flex: 1,
  },
  promiseTitle: {
    fontSize: Typography.subheadline.fontSize,
    fontWeight: Typography.subheadline.fontWeight as any,
    color: Colors.textPrimary,
    marginBottom: Spacing.compact,
  },
  description: {
    fontSize: Typography.body.fontSize,
    color: Colors.textSecondary,
    lineHeight: 20,
  },
  setupQuestion: {
    fontSize: Typography.subheadline.fontSize,
    fontWeight: Typography.subheadline.fontWeight as any,
    color: Colors.textPrimary,
    marginBottom: Spacing.tight,
    textAlign: "center",
  },
  setupSubtext: {
    fontSize: Typography.body.fontSize,
    color: Colors.textSecondary,
    textAlign: "center",
    marginBottom: Spacing.loose,
  },
  toggleButtons: {
    flexDirection: "row",
    gap: Spacing.default,
    marginBottom: Spacing.loose,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: Spacing.default,
    borderRadius: 8,
    borderWidth: 2,
    borderColor: Colors.glass,
    alignItems: "center",
  },
  toggleActive: {
    backgroundColor: Colors.leaf,
    borderColor: Colors.leaf,
  },
  toggleText: {
    fontSize: Typography.button.fontSize,
    fontWeight: Typography.button.fontWeight as any,
    color: Colors.textPrimary,
  },
  toggleTextActive: {
    color: "#FFFFFF",
  },
  referralInput: {
    borderWidth: 1,
    borderColor: Colors.glass,
    borderRadius: 8,
    paddingHorizontal: Spacing.default,
    paddingVertical: Spacing.default,
    fontSize: Typography.body.fontSize,
    color: Colors.textPrimary,
    marginBottom: Spacing.default,
  },
  referralNote: {
    fontSize: Typography.caption1.fontSize,
    color: Colors.textDisabled,
    fontStyle: "italic",
  },
  bottomSection: {
    marginBottom: Spacing.default,
  },
  disclaimer: {
    fontSize: Typography.caption2.fontSize,
    color: Colors.textDisabled,
    textAlign: "center",
    marginTop: Spacing.default,
  },
});
